### ISSUE TITLE
User authorization

### ISSUE THREAD

**Issue by PosterHero** [Waterboy1602/Addarr#4]
Is there a possibility to add a username and password for entering the chat with the addarr bot? Like authorization.

Example: https://gitlab.com/herpaderk/tgrsbot

**Comment by Waterboy1602** [comment]
I've looked into that code and didn't directly found an example where you have to enter a username and password. The username and password you have to enter in the config of _tgrsbot_ were for radarr and sonarr.

I could implement a feature that only specific groupchatids are allowed to chat with your bot. Is it that what you were implicating?

**Comment by PosterHero** [comment]
Sorry, i posted wrong project. https://github.com/eamondo2/telegram-radarr-bot?files=1

Look at the acl.json

**Comment by Waterboy1602** [comment]
I've found the auth part in that project. I just don't quite get it why I should do this. When you don't share your TelegramBot API, it's secure I assume. Except you could convince me?

**Comment by PosterHero** [comment]
Bots can't initiate conversations with users. A user must either add them to a group or send them a message first. People can use telegram.me/<bot_username> links or username search to find your bot..

So by default anyone can access your, on his name..

**Comment by Waterboy1602** [comment]
That's something I didn't know. Thanks for the explanation! I will look into it to make this chatbot more secure. I will make an `/auth` command that you need to execute the first time.

**Comment by PosterHero** [comment]
Creat job! Thnx for your work

**Comment by schoentoon** [comment]
You could also implement a whitelist of user id's that would actually be allowed to interact with the bot at all instead. Would be quite easy to implement and would achieve the same goal.

**Comment by Waterboy1602** [comment]
That's indeed also a possibility how to implement this.

I was thinking to implement it like this. Before you could use the bot, you should execute an /auth command with password. Then when it's the right password, the chatid will be added to a whitelist of allowed chatid's. And every time you use the bot, this will be checked.

**Comment by schoentoon** [comment]
Wouldn't it make more sense to make `/start` prompt for a password instead of requiring the user to call `/auth <password>`? Especially because a new conversation with a bot on Telegram will automatically send `/start`.

**Comment by Waterboy1602** [comment]
That's indeed a better way to handle this. I will soon change it to this. So the first time you enter the bot. Telegram will send `/start` and then the bot will ask for the password. If it's it correct, your chatid will be saved to a file. Does this sound alright to you?

**Comment by schoentoon** [comment]
That would sound perfect yes. Could you however specify what file? Odds are the strange behavior I have with the docker image is directly related to this. As in if I restart the process of the bot I have to message `/start` again to get it to work at all.

**Comment by Waterboy1602** [comment]
Now it's saved to `chatid.txt`. So every time a chat is authorized, the bot will write the chatid int to this file.

**Comment by PosterHero** [comment]
Great work, I'll try it tomorrow :blush:

**Comment by schoentoon** [comment]
It works, but it is flawed and that should probably be fixed ASAP.
You probably only tested this with a single user, in the case of multiple users the chat id's are simply appended after each other without any form of delimiter. As a result, if my user id would be 1 and yours would be 2, then the contents of chatids.txt would be 12. Naturally granting access to user with id 12 as well. New line delimiting would already be enough to fix this.

**Comment by Waterboy1602** [comment]
I fixed it. Thanks for letting me know!

**Comment by schoentoon** [comment]
I would say that it's still not entirely fixed though. You should probably read out the file line by line and check the complete line. If my id would be 12 and user with 1 or 2 would try to use this service it would still work.

**Comment by Waterboy1602** [comment]
I've made a fix for it. Now it reads line by line. I don't think my fix is the most efficient one. When I have more time I will look to change it.

**Comment by PosterHero** [comment]
Feature works great now, multiple chatids.
But what about logging when someone enters the wrong password? (audit)

**Comment by Waterboy1602** [comment]
Is a great idea. I will surely add this later!

**Comment by Waterboy1602** [comment]
The latest release consist of the added audit function. The audit is saved to the logfile.
